# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 박시현
title: Backend Developer
email: tyakamyz@naver.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://tong-dev.tistory.com/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: tyakamyz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  7년 차 Java & Spring 기반 Backend 업무를 담당하고 있는 박시현입니다.<br>
  SI/SM 사업 & 스타트업 재직 경험을 통하여 <mark>다양한 분석/설계 경험</mark>을 가지고 있습니다.<br>
  
  주도적으로 프로젝트 내에 개선점을 찾기 위해 노력하여,<br>
  기존 관리 시스템 솔루션에서 서비스 페이지를 운영할 수 있도록 고도화하였습니다.<br>
  그로 인해 개발 공수를 줄이고, 회사 매출에 <mark>큰 기여를 한 경험</mark>이 있습니다.<br>
  
  또한, 꾸준한 성장을 위해 '우아한 테크캠프 Pro' 4기에 참가하여 <mark>우수 수료생</mark>으로 교육을 이수하였습니다.

content:
  - title: 경력 (6년 2개월)
    layout: list
    content:
      - layout: left
        title: 스카이랩스
        sub_title: 백엔드 개발자
        caption: 2020.07 ~ 2022.05
        link: https://skylabs.io/ko/
        quote: >
          IoT 기술을 활용한 웨어러블 모니터링 서비스
        description: | # this will include new lines to allow paragraphs
          - 구독 결제 서비스 개발
          - 서버 성능 개선
          - APP & WEB 서버 개발 및 운영
      - layout: left
        title: 한국문헌정보기술
        sub_title: 웹 개발자
        caption: 2016.03 ~ 2020.07
        link: http://www.kait.co.kr/
        quote: >
          수집/기록 관리시스템 SI/SM 구축 사업
        description: | # this will include new lines to allow paragraphs
          - 서비스 기능을 고도화한 [감어인M](http://archivecenter.net/kait/archive/Webpage.do?page_id=59) 솔루션 개발
          - 색상 검색 기능 개발
          - 2명의 그룹원을 이끄는 <mark>그룹장</mark>으로 PL업무 수행
  - title: 대표 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 구독 결제 서비스
        sub_title: 스카이랩스
        caption: 2021.09 ~ 2022.03
        quote: >
          결제 상품 및 배송 서비스 관리가 가능한 시스템 구축
        description: | # this will include new lines to allow paragraphs
          - 국/외 결제와 배송 관리 등 복잡한 프로세스의 대한 분석 및 설계
          - 단건 결제와 월정기 결제가 가능하도록 개발
            - 국내 결제: payple 결제 모듈
            - 해외 결제: paypal 결제 모듈
          - 사업상 문제로 오픈이 지연되어 결제 기능과 배송 처리 기능만 구현
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
        title: 서버 성능 개선
        sub_title: 스카이랩스
        quote: >
          python 기반의 서버 인프라 개선 경험. 메모리 초과로 인한 다운 현상 & 불안정한 서버 환경 개선
        description: | # this will include new lines to allow paragraphs
          - Jmiter, NewRelic 어플리케이션을 사용하여 [부하 테스트 및 모니터링 진행](https://tong-dev.tistory.com/30?category=959546)
          - 메모리 초과 장애 개선
          - 동일한 서버 비용으로 더 많은 트래픽을 처리할 수 있도록 개선
      - layout: left
        title: 감어인M 솔루션 개발
        sub_title: 한국문헌정보기술
        caption: 2018.07 ~ 2018.12
        quote: >
          기존 수집관리시스템 솔루션에 서비스 관리 기능을 추가하여 서비스 페이지를 운영할 수 있도록 고도화
        description: | # this will include new lines to allow paragraphs
          - 서비스 메뉴를 생성하여 서비스 페이지를 연계할 수 있는 기능 개발
          - 엑셀 파일을 업로드하여 대량의 데이터를 일괄 업로드 할 수 있는 기능 개발
          - 반복적으로 발생하는 요구사항을 처리하여 개발 공수 감소
          - 안정적으로 프로젝트 수행 완료. 이후 타 사업에서 [감어인M](http://archivecenter.net/kait/archive/Webpage.do?page_id=59)이라는 명칭의 패키지 솔루션으로 납품하여 회사 매출에 큰 기여를 하는 성과를 거둠
      - layout: left
        title: 색상 검색 기능 개발
        sub_title: 한국문헌정보기술
        caption: 2018.07 ~ 2018.12
        quote: >
          업로드된 이미지 파일의 대표 색상을 추출하여, 색상 검색이 가능하도록 기능 개발
        description: | # this will include new lines to allow paragraphs
          - [오픈 소스](https://github.com/SvenWoltmann/color-thief-java)와 Color 클래스를 활용하여 대표 색상을 추출한 뒤 RGB 색상 모델을 HSB 색상 모델로 변경하여 범위값을 도출하는 방식으로 개발
          - 9가지 대표 색상으로 검색 가능하도록 개발

  - title: 보유 스킬
    layout: list
    content:
      - layout: left
        title: BackEnd
        description: | # this will include new lines to allow paragraphs
          - Java
          - Spring, Spring Boot
          - JPA, myBatis, iBatis
          - Junit5, Mockito
          - Maven
          - IntelliJ
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Oracle, Cubrid, MariaDB
          - DynamoDB, S3
          - Tomcat, Jeus
          - Jenkins, Docker
          - Git, SVN
      - layout: left
        title: 자격증
        description: | # this will include new lines to allow paragraphs
          - CCNA
          - SQLD
          - 리눅스마스터 2급
          - 정보처리기사

  - title: 교육
    layout: list
    content:
      - layout: left
        title: 우아한 테크캠프 Pro 4기
        link: https://edu.nextstep.camp/c/lqsBs7x0/
        caption: 2022.05 ~ 2022.07
        quote: >
          경력자를 대상으로 진행하는 과제 형식의 교육 참가
        description: | # this will include new lines to allow paragraphs
          - 2주일 간의 프리코스를 통해 60명 선발 (4기 경쟁률 약 7:1)
          - <mark>우수 수료생</mark>으로 교육 이수 완료 (전체 수료율 63%)
          - 클린코드, JPA 기반의 웹 개발, 단위 테스트(TDD)와 인수 테스트(ATDD) 기반의 웹 개발, <mark>레거시 코드 리팩터링</mark>, 시스템 아키텍처를 설계 및 운영, 웹 성능 최적화 및 튜닝
  - title: 기타 정보
    layout: list
    content:
      - layout: left
        title: 개인 블로그
        link: https://tong-dev.tistory.com/
        description: | # this will include new lines to allow paragraphs
          학습한 내용과 업무 경험 등을 정리한 개인 블로그 입니다.
      - layout: left
        title: 상세 기술경력서
        link: https://github.com/tyakamyz/tyakamyz.github.io/raw/main/file/SiHyun_Career_Description.pdf
        link_text: PDF 파일 다운로드
        description: | # this will include new lines to allow paragraphs
          경력 및 프로젝트 내용을 상세하게 기술한 PDF 파일입니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
